[package]
name = "nova-software-common"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = { version = "0.7.7", features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = ["serde/std"]
