[package]
name = "novafc-flight"
version = "0.1.0"
edition = "2021"

[dependencies]
novafc-common = { path = "../common/" }
heapless = "0.7.7"
static-alloc = "0.2.3"
novafc-config-format = { path = "../config-format/" }
novafc-data-format = { path = "../data-format/" }
