[package]
name = "novafc-flight"
version = "0.1.0"
edition = "2021"

[dependencies]
# novafc-common = { path = "../common/", default-features = false }
heapless = "0.7.7"
static-alloc = "0.2.3"
# novafc-config-format = { path = "../config-format/", default-features = false }
# novafc-data-format = { path = "../data-format/", default-features = false }

embedded-hal = "0.2"
nb = "1"
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
shared-bus = "0.2.3"

h3lis331dl = { git = "https://github.com/ERFSEDS/h3lis331dl" }
bmi088 = "0.1.0"

[dependencies.stm32f4xx-hal]
version = "0.12.0"
features = ["stm32f401"]

[dependencies.ms5611-spi]
version = "0.2.0"
default-features = false
features = ["ms5607"]
