[package]
name = "novafc-flight"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.7.7"
static-alloc = "0.2.3"
novafc-config-format = { path = "../config-format/", default-features = false }
novafc-data-format = { path = "../data-format/" }

embedded-hal = "0.2"
nb = "1"
cortex-m = "0.7"
cortex-m-rt = "0.6"
panic-halt = "0.2"
stm32f4xx-hal = { version = "0.9", features = ["rt", "stm32f401"] }
